package com.example.bubblelayout.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.bubblelayout.Head;
import com.example.bubblelayout.StudentEntity;
import com.example.bubblelayout.TeacherEntity;
import com.example.bubblelayout.entity.ChatMessageEntity;

import com.example.bubblelayout.db.HeadDao;
import com.example.bubblelayout.db.StudentEntityDao;
import com.example.bubblelayout.db.TeacherEntityDao;
import com.example.bubblelayout.db.ChatMessageEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig headDaoConfig;
    private final DaoConfig studentEntityDaoConfig;
    private final DaoConfig teacherEntityDaoConfig;
    private final DaoConfig chatMessageEntityDaoConfig;

    private final HeadDao headDao;
    private final StudentEntityDao studentEntityDao;
    private final TeacherEntityDao teacherEntityDao;
    private final ChatMessageEntityDao chatMessageEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        headDaoConfig = daoConfigMap.get(HeadDao.class).clone();
        headDaoConfig.initIdentityScope(type);

        studentEntityDaoConfig = daoConfigMap.get(StudentEntityDao.class).clone();
        studentEntityDaoConfig.initIdentityScope(type);

        teacherEntityDaoConfig = daoConfigMap.get(TeacherEntityDao.class).clone();
        teacherEntityDaoConfig.initIdentityScope(type);

        chatMessageEntityDaoConfig = daoConfigMap.get(ChatMessageEntityDao.class).clone();
        chatMessageEntityDaoConfig.initIdentityScope(type);

        headDao = new HeadDao(headDaoConfig, this);
        studentEntityDao = new StudentEntityDao(studentEntityDaoConfig, this);
        teacherEntityDao = new TeacherEntityDao(teacherEntityDaoConfig, this);
        chatMessageEntityDao = new ChatMessageEntityDao(chatMessageEntityDaoConfig, this);

        registerDao(Head.class, headDao);
        registerDao(StudentEntity.class, studentEntityDao);
        registerDao(TeacherEntity.class, teacherEntityDao);
        registerDao(ChatMessageEntity.class, chatMessageEntityDao);
    }
    
    public void clear() {
        headDaoConfig.clearIdentityScope();
        studentEntityDaoConfig.clearIdentityScope();
        teacherEntityDaoConfig.clearIdentityScope();
        chatMessageEntityDaoConfig.clearIdentityScope();
    }

    public HeadDao getHeadDao() {
        return headDao;
    }

    public StudentEntityDao getStudentEntityDao() {
        return studentEntityDao;
    }

    public TeacherEntityDao getTeacherEntityDao() {
        return teacherEntityDao;
    }

    public ChatMessageEntityDao getChatMessageEntityDao() {
        return chatMessageEntityDao;
    }

}
